import { indexOfWithDist } from './distsearch.js';

const verylongstring = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent hendrerit id massa sagittis euismod. Curabitur interdum felis urna, quis finibus erat luctus vitae. Phasellus eu consequat ante. Vestibulum pretium semper felis, ut finibus mi euismod a. Sed pellentesque orci vel felis venenatis finibus. Aenean placerat ante eget hendrerit elementum. Nulla tincidunt eu ante ac malesuada. Praesent leo sem, dictum nec pellentesque ac, congue a dui. Curabitur auctor nunc ac odio ornare, commodo elementum turpis dignissim. Integer ac consectetur nisl. Sed diam magna, tristique quis dapibus eget, luctus nec velit. Nullam faucibus justo turpis, eu bibendum ipsum pellentesque non. \
 \
Morbi vehicula tortor a fermentum faucibus. Suspendisse accumsan, arcu eu varius egestas, ante enim euismod nunc, in auctor velit mauris id elit. Donec at congue augue. Nulla elementum scelerisque consectetur. Donec aliquet ultrices ipsum et semper. Nullam mattis quam ipsum, vitae interdum arcu hendrerit eget. Morbi lacus ante, suscipit nec scelerisque vel, finibus a justo. Sed non condimentum sem, in semper mi. Morbi et sapien viverra, sagittis dui et, porta dolor. \
 \
Proin aliquam varius lacinia. In ultrices lacus dolor, non sollicitudin erat suscipit sit amet. Nullam fringilla mi ut pharetra rhoncus. Etiam commodo sollicitudin ultricies. Donec dolor quam, efficitur at elit ac, consequat pellentesque enim. In hac habitasse platea dictumst. Mauris ac neque scelerisque purus luctus sollicitudin. Proin tempus lacus turpis, at sollicitudin dolor sagittis eu. \
 \
Cras a facilisis felis, sit amet efficitur purus. Curabitur in varius risus, vel commodo augue. Etiam lectus nibh, tempus id rutrum mattis, fringilla vitae ex. Sed sed risus finibus, finibus est vitae, dictum nulla. Vivamus eu dictum lectus. Quisque vitae vestibulum est. Aenean sit amet imperdiet turpis. Nulla tincidunt enim ac tristique viverra. \
 \
Vestibulum gravida bibendum nisi, ut mollis sem pretium nec. Duis faucibus justo eleifend nunc tincidunt, ac venenatis risus condimentum. Mauris tincidunt sodales ex sit amet rhoncus. Quisque ac dignissim leo. Nunc accumsan gravida fermentum. Etiam arcu lectus, tincidunt in semper aliquet, consequat ac lorem. Etiam viverra dui non laoreet luctus. Morbi fringilla aliquet tellus, eget gravida erat volutpat vel. Pellentesque cursus commodo elementum. Fusce maximus massa sed enim faucibus porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam erat volutpat. Etiam dignissim semper urna ac porta. Proin felis lacus, rutrum sit amet cursus nec, commodo eu ante. \
 \
Donec laoreet mauris a orci porta egestas. Donec vel tellus tellus. Quisque semper augue nibh, ac interdum dui ultrices et. Praesent eget ultrices ante. Praesent vestibulum, purus vitae mattis laoreet, purus sem varius odio, quis vulputate lorem sapien quis dui. In sollicitudin massa et bibendum commodo. Nulla sit amet arcu nunc. Suspendisse mattis rutrum orci non efficitur. Cras scelerisque, tellus quis porta scelerisque, nunc erat ullamcorper neque, ut sodales lectus neque ac ante. \
 \
Fusce varius interdum pharetra. Proin et nulla at leo convallis hendrerit. Praesent imperdiet massa nec purus gravida, eget posuere felis egestas. Suspendisse vitae risus odio. Nam quis tellus placerat, faucibus augue vel, porttitor ante. Nunc ex quam, hendrerit et enim non, lacinia elementum est. Donec nisi erat, feugiat sit amet convallis sed, congue at ipsum. Sed posuere bibendum tellus id commodo. Suspendisse ornare, diam in rhoncus placerat, sem ligula eleifend lorem, sit amet feugiat orci justo sed velit. Quisque rhoncus enim eget odio commodo interdum in vel purus. Donec imperdiet tellus ut nibh aliquet, id volutpat ligula cursus. Vivamus dictum diam in lacus ultricies vulputate. \
 \
Vestibulum gravida justo ut lorem consequat, porta bibendum nisl tempus. Donec ultricies erat volutpat, varius leo a, ultrices felis. Duis ultrices ligula sed tristique euismod. Aenean ut augue malesuada, finibus velit eget, pulvinar tortor. Quisque ultrices sodales tempus. Praesent pretium nulla ac felis pharetra, id vestibulum odio volutpat. Aenean sodales mauris non tortor sollicitudin, sit amet eleifend nisi elementum. Praesent accumsan non magna in venenatis. Duis rutrum risus enim, quis tristique diam condimentum nec. \
 \
Ut consequat efficitur odio, sit amet pulvinar leo pretium in. Ut odio est, condimentum a fermentum quis, dignissim nec dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum iaculis eros vitae congue dictum. Donec ultrices pellentesque erat, a accumsan lectus interdum a. Integer sollicitudin velit justo, ac pharetra dolor porta nec. In hac habitasse platea dictumst. Fusce leo mi, auctor et sapien nec, rhoncus molestie justo. Duis a rutrum massa. Morbi porta eu lorem quis ornare. \
 \
Morbi porta bibendum efficitur. Fusce justo nunc, pretium vel dolor eget, laoreet fringilla magna. Pellentesque sit amet placerat nunc. Sed in ex nec velit feugiat tincidunt. Proin a eleifend purus, eget congue mi. Maecenas massa est, vehicula a massa at, pretium mollis libero. Morbi eros diam, hendrerit non vehicula sit amet, placerat at dolor. Nulla placerat ipsum at felis vulputate, non placerat ipsum egestas. Morbi finibus facilisis molestie. Sed mi tortor, gravida eget gravida nec, convallis molestie ipsum. Sed eu ultrices lacus, a porta sapien. Proin feugiat odio tortor, eu iaculis neque sagittis sed. Ut non interdum leo. \
 \
Nulla posuere augue arcu, et maximus neque pulvinar nec. In sodales neque a nulla interdum vehicula. Suspendisse in eros risus. Vestibulum ullamcorper nibh sed quam rhoncus, et maximus enim faucibus. Aenean vel nisl leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ligula velit, lobortis eu viverra et, ultrices in neque. Sed risus diam, aliquet luctus ornare vel, sagittis vitae sem. Nam pharetra eros vel leo iaculis feugiat. Maecenas nec lorem malesuada, cursus ipsum in, euismod leo. Duis rhoncus varius mi. In velit metus, fermentum quis fringilla vel, lacinia sit amet elit. \
 \
Vivamus at porta nulla, quis ornare massa. Sed iaculis eu nulla at laoreet. Cras commodo tincidunt nisl, a suscipit mi mollis ullamcorper. Integer leo tortor, sollicitudin eget dictum eu, mollis ac tortor. Quisque rutrum commodo metus vitae semper. Ut rutrum, justo pellentesque pretium egestas, ante lorem dapibus orci, eget volutpat erat leo sit amet turpis. Curabitur sodales quam et porta tristique. Aenean nec fermentum metus, ut rhoncus nisi. \
 \
Vivamus malesuada efficitur est sit amet porttitor. Sed nec nunc augue. Morbi nisl magna, scelerisque in commodo eget, maximus sed libero. Cras posuere turpis condimentum pharetra commodo. Maecenas vel facilisis justo. Nullam lacinia sem id purus accumsan luctus. Praesent aliquet sodales sodales. Etiam molestie metus nulla, ut lacinia diam ullamcorper quis. Vestibulum quis urna facilisis, porttitor ex id, blandit lectus. Nullam mollis venenatis ante, vitae luctus nisl viverra ac. Aliquam eu fermentum nulla, venenatis volutpat sapien. Nulla ac risus vitae erat egestas sollicitudin. Etiam non nulla et turpis elementum scelerisque. \
 \
Curabitur viverra, sem ut mattis dapibus, enim lorem iaculis arcu, a placerat erat tortor sed purus. Ut dapibus ex ante, eget suscipit mauris commodo ac. Praesent condimentum purus sit amet diam eleifend, ut feugiat neque suscipit. Nunc ac condimentum urna. Aenean viverra sodales elit non semper. Nulla sollicitudin urna nulla, quis scelerisque nisi tincidunt eu. Phasellus pellentesque pharetra arcu, id posuere dolor tempus ac. Ut ac sagittis magna. Maecenas rutrum at felis ac bibendum. Aliquam mauris nunc, ornare eu ligula eget, maximus tempus mi. Sed tempus fermentum mauris eu tristique. Mauris volutpat lobortis suscipit. Praesent tempus sodales fermentum. Duis ultricies facilisis ipsum et porttitor. Aenean vitae tempus enim. Proin volutpat consequat leo vitae vehicula. \
 \
Fusce pellentesque, tellus in placerat convallis, justo dolor porta ligula, eget varius felis ex id sem. Quisque varius libero magna, eget consectetur tellus aliquam ultrices. Fusce ullamcorper semper massa, eget suscipit sapien tincidunt at. Nulla facilisi. Aenean nec libero tincidunt, feugiat felis sit amet, sodales velit. Vivamus id felis facilisis, condimentum justo sed, viverra dolor. Nullam eget porta lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ut elit sit amet mi pretium euismod. Pellentesque sapien ex, porttitor elementum finibus non, luctus ut sapien. Donec vel condimentum diam, et blandit urna. In hac habitasse platea dictumst. \
 \
Aenean ac quam sit amet quam venenatis luctus. Praesent scelerisque nec mauris in malesuada. Praesent orci ex, congue sit amet elit nec, posuere placerat felis. Cras ullamcorper, diam vitae vulputate venenatis, velit orci venenatis diam, vel tempus nibh quam at tortor. Morbi imperdiet dolor at eleifend placerat. Nulla dignissim dolor augue, nec dignissim sapien sollicitudin sit amet. Nam mattis nisl id est pulvinar, vitae laoreet diam hendrerit. Donec velit velit, ultrices nec ligula sed, efficitur vulputate nisl. In ac dui sed ex egestas vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut faucibus mi et risus venenatis, vitae dignissim nibh condimentum. Vivamus vel dui lacinia dui pharetra tristique in in eros. \
 \
Etiam gravida urna ullamcorper ipsum malesuada interdum. Nulla mollis tortor ut consequat finibus. Ut nec lorem eros. Etiam lacinia quam augue. Sed tortor diam, ultrices vel orci eget, porttitor semper tellus. Nunc in ipsum a nulla ultrices finibus. Pellentesque nec facilisis leo, fermentum ornare ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; \
 \
Vivamus mi sapien, cursus at dictum ac, fermentum vel massa. Cras lacus tortor, sollicitudin maximus purus non, interdum elementum dolor. Nam sit amet massa ac sem ullamcorper pellentesque non in ex. In dictum lacus quis lectus iaculis, at sodales sapien consequat. Vestibulum porta dolor eu accumsan pretium. Cras accumsan posuere diam, quis consequat ex. Nulla facilisi. \
 \
Aliquam rhoncus imperdiet rutrum. Ut finibus pellentesque nisl, at volutpat tellus ultricies quis. Nulla facilisi. Sed id lacinia leo. Nam consequat fringilla euismod. Etiam ut nulla porta, sodales lectus a, ornare eros. Suspendisse eros tellus, congue non pulvinar id, vestibulum aliquet orci. Maecenas maximus, massa id eleifend commodo, lorem urna vulputate risus, id iaculis est felis ut erat. Cras eu sapien ex. Sed viverra libero eu elit malesuada, vitae porttitor sapien rutrum. Suspendisse ante arcu, mollis id quam eget, aliquam mattis velit. Phasellus pulvinar purus sit amet velit pharetra ullamcorper. Fusce blandit finibus commodo. Nullam hendrerit lorem vel ex venenatis mollis. Mauris odio est, interdum rutrum velit non, laoreet sodales eros. \
 \
Nulla malesuada mi diam, non aliquam risus ultrices sit amet. Nullam tempor lacus sit amet nulla porta efficitur. Sed sit amet hendrerit eros, vel condimentum tortor. Proin non felis eu sem iaculis pellentesque at eu lectus. Donec et justo arcu. Aenean et convallis felis, et dignissim eros. Suspendisse non sem lectus. \
 \
Quisque pellentesque arcu sed pharetra aliquam. Etiam eu sapien lorem. Aliquam sodales euismod nulla eu malesuada. Phasellus euismod elit sed ligula cursus, fermentum dictum turpis pretium. Curabitur aliquam tortor vitae vestibulum porta. Maecenas pulvinar, diam non mattis tincidunt, risus justo tincidunt mauris, id viverra ipsum augue at nulla. In condimentum lacinia sapien at condimentum. Duis pellentesque sodales mi id ullamcorper. Suspendisse quis elit turpis. Donec tincidunt arcu id justo convallis tempor. Etiam efficitur molestie facilisis. \
 \
Ut cursus non purus finibus imperdiet. Donec vel placerat libero. Praesent lacinia tortor sem, sed vestibulum mauris fringilla ut. Nullam in sapien tristique, malesuada odio ac, imperdiet dolor. Cras ultrices fringilla dui, vitae rutrum odio sodales a. Suspendisse scelerisque, magna sed scelerisque egestas, dolor diam consectetur nisi, consectetur dignissim orci justo a neque. Cras lacinia vestibulum ex in pretium. Cras feugiat quis velit at efficitur. Proin rhoncus suscipit quam a congue. \
 \
Interdum et malesuada fames ac ante ipsum primis in faucibus. In non bibendum quam. Etiam eu mattis odio. In hac habitasse platea dictumst. Quisque eget mattis tellus, at semper dolor. Cras euismod imperdiet erat, a auctor enim convallis sed. Sed at nulla urna. Praesent non quam lobortis orci tristique euismod. Pellentesque eu risus at justo posuere pharetra a id lectus. Fusce semper nulla et ex aliquam gravida. Curabitur finibus nibh porta leo mattis, lobortis faucibus nisi volutpat. Etiam at sodales nisi. Fusce suscipit interdum arcu, quis accumsan nunc suscipit ut. Duis ante libero, maximus nec lectus nec, faucibus tincidunt diam. Proin in arcu ac erat faucibus lobortis ac ut velit. \
 \
Nulla volutpat placerat mi non volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc interdum consequat tortor, id euismod neque fermentum sit amet. Mauris rutrum, felis quis efficitur molestie, magna mi pellentesque ligula, eget cursus tortor risus ut neque. In vestibulum sapien eget ex dapibus, vel tincidunt massa fermentum. Pellentesque eget dapibus risus. Aenean in gravida lorem, in fermentum velit. Praesent eget pharetra dolor. Praesent nec dignissim velit. Etiam molestie, dui non dapibus lobortis, erat odio rutrum risus, at luctus odio lectus non arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque nec cursus ipsum. \
 \
Nulla eget quam vel libero placerat condimentum non sed arcu. Etiam in turpis ligula. Ut molestie hendrerit quam. Etiam porta ante ullamcorper ipsum pulvinar, in tempor metus finibus. Integer ut lacus at nibh condimentum eleifend. Fusce euismod a metus sit amet tempor. Curabitur porta lectus vel elit semper eleifend. In nec varius dolor. In dapibus iaculis arcu, id ornare massa semper rhoncus. Nulla efficitur eu est non cursus. Morbi rutrum, est a lobortis rutrum, elit nisi pellentesque purus, vitae varius lectus leo non augue. Nullam vehicula leo nec sodales faucibus. Nunc ultricies aliquet est, eu vestibulum mauris finibus sit amet. Maecenas interdum dolor augue, in scelerisque nisi pharetra non. Ut ut nulla non est vehicula varius. \
 \
Maecenas eget interdum orci, ac tristique metus. Donec mattis consequat neque, et commodo turpis ultrices eu. Proin faucibus pulvinar eleifend. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc elementum ligula sed vulputate scelerisque. Nullam efficitur venenatis quam vel rhoncus. Donec convallis molestie molestie. Maecenas dignissim sapien fermentum urna placerat, quis malesuada diam mattis. Pellentesque at maximus purus, euismod auctor velit. Sed venenatis mauris id elit euismod mollis. Suspendisse maximus ullamcorper tempus. \
 \
Suspendisse euismod turpis ac maximus imperdiet. Ut nec dapibus lorem. Nulla ut tristique sem. Sed augue nunc, condimentum et libero a, lobortis accumsan lectus. Quisque nec eros sed urna faucibus viverra non non nisl. In vitae mi vel libero porta vehicula non ac urna. Suspendisse venenatis placerat dolor, vitae accumsan nisl ultrices a. Suspendisse potenti. Nam feugiat vestibulum quam, et sodales felis tincidunt a. Aliquam sodales nisl dui, sed malesuada erat facilisis quis. \
 \
Suspendisse consectetur lacus in orci blandit ultrices. Proin a tellus congue, dictum ex sagittis, semper elit. Donec in auctor nulla. Ut ac nibh eu dolor posuere fringilla. Aenean vulputate hendrerit tincidunt. Vivamus at dictum risus. Duis ultrices, elit vel euismod fringilla, massa tellus faucibus augue, vitae feugiat tellus lectus sed augue. Donec eget neque finibus, luctus nibh et, laoreet libero. \
 \
Nullam convallis fringilla lectus, tincidunt sollicitudin est scelerisque id. Donec suscipit tincidunt libero. Praesent nec mi diam. Integer auctor hendrerit semper. Curabitur rutrum lorem nec felis posuere, id sodales tellus venenatis. Nunc lacinia neque nisi, vitae pellentesque ex luctus non. Sed eget ligula eros. Maecenas eu pretium mauris. Nunc semper elementum ex, non imperdiet risus vestibulum auctor. \
 \
Proin in tincidunt lacus. Nulla ligula nisl, gravida et leo eget, ullamcorper laoreet dolor. Donec malesuada et sem quis condimentum. Fusce commodo, arcu eu ornare bibendum, lorem justo convallis ante, in dapibus eros ipsum vitae ante. Aenean sit amet enim vitae tellus varius volutpat. Quisque mollis eu tortor in dapibus. Etiam rutrum nunc id erat commodo, ac interdum magna semper. Praesent augue justo, lobortis ac est eget, convallis aliquet dui. Nunc ac augue ut lacus elementum eleifend. Maecenas placerat tortor lorem, ac convallis lacus venenatis pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse molestie turpis at posuere ultricies. Ut placerat ac risus non blandit. Sed at sapien vel mi interdum semper. Ut porta, mi non commodo tempus, eros est dapibus metus, a tempus neque eros vel nisl. Vestibulum eu cursus mauris. \
 \
Cras vel rhoncus arcu, vel egestas sapien. Aenean laoreet nulla feugiat ante volutpat feugiat. Curabitur egestas porta sodales. Nunc odio risus, ultrices sit amet varius vel, bibendum ac eros. Morbi leo magna, sagittis eu mauris non, varius sodales mauris. Nullam cursus eros posuere volutpat placerat. Nam tincidunt dignissim luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur sit amet nisi ut purus tincidunt mollis. Proin tristique at tellus ut imperdiet. Suspendisse leo dolor, dapibus vitae augue eu, ullamcorper dictum sem. Vivamus malesuada rutrum sem sit amet eleifend. \
 \
Vivamus eu risus ornare, tempor nulla non, consequat dolor. Praesent placerat finibus cursus. Phasellus at porta turpis. Mauris euismod non tellus non semper. In aliquet nibh et libero suscipit, in rutrum tellus condimentum. Fusce mattis lacinia ipsum, nec vestibulum mauris. Donec euismod sodales lorem ut iaculis. Donec volutpat fermentum efficitur. Nam vestibulum aliquet mi eget commodo. \
 \
Mauris cursus elementum quam. Nullam eu leo vel purus porttitor rutrum eget sit amet diam. Proin nunc purus, tempor sed dignissim id, tristique at ipsum. Aenean tempor, enim ut ultrices tempus, libero nisi tempus odio, vitae sodales lacus dolor in magna. Integer finibus eros elit, consequat hendrerit dolor fringilla fermentum. Aliquam tristique velit elementum risus fermentum, sed sagittis tortor tincidunt. Quisque dictum elementum ante vitae luctus. Vivamus sagittis consequat enim vel semper. Ut posuere mauris non diam cursus finibus. Cras convallis magna gravida mauris mattis blandit. Fusce sapien arcu, interdum eget efficitur dictum, molestie eget quam. Suspendisse a euismod justo. Proin accumsan mi quam, ut consectetur dolor dignissim nec. In cursus elementum orci nec pellentesque. Pellentesque et luctus nisi, quis mattis ligula. \
 \
Suspendisse eget metus convallis, lacinia mauris eget, commodo dui. Etiam cursus lacus a neque efficitur porttitor. Nullam ac sollicitudin quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent tempus diam a pharetra accumsan. Duis gravida consequat sagittis. Sed quis arcu in nulla finibus aliquam. Nulla hendrerit luctus tortor, vitae fermentum metus faucibus et. Praesent tempor massa vel neque volutpat sodales. Mauris hendrerit eros sed tortor vestibulum, sit amet egestas lacus pretium. Mauris pretium metus id nibh vulputate, in convallis mi laoreet. \
 \
Morbi ornare in ante sagittis aliquet. Vestibulum eu semper elit, eget viverra mi. Cras tellus nulla, posuere ut dapibus et, eleifend ut eros. Quisque et purus nisi. Nullam tincidunt justo vitae fermentum semper. Morbi ut posuere neque. Integer dolor est, consequat quis sollicitudin et, hendrerit vitae tortor. Etiam cursus lacinia iaculis. Donec varius sapien consequat lorem bibendum, ut tempus metus tincidunt. Duis sollicitudin metus ac elit dictum hendrerit elementum porttitor mauris. Donec consequat metus ut elit rhoncus elementum. Vivamus lobortis arcu diam, eu ullamcorper dolor fringilla sit amet. \
 \
Phasellus convallis tempus libero, in feugiat nulla dapibus eget. Etiam sollicitudin, tellus vitae volutpat laoreet, velit ante blandit nibh, ac rutrum ligula quam nec felis. Nulla egestas, quam nec eleifend posuere, mi dui porttitor leo, at semper risus leo at eros. Cras dui tellus, porttitor eu pretium ut, posuere at ante. Etiam ut sodales diam, id malesuada magna. Sed porta felis nec mi posuere, sed aliquet diam feugiat. Phasellus ac rhoncus mauris, vel commodo ligula. \
 \
Fusce vitae dapibus libero. Sed scelerisque vehicula neque, eget pellentesque nisl tincidunt in. Nunc accumsan erat nunc, ac fermentum orci porttitor id. Duis accumsan, metus ut fringilla scelerisque, diam orci lobortis risus, sed elementum diam massa feugiat lectus. Nam a scelerisque dui, gravida aliquam nisi. Etiam sed nunc fringilla, sagittis felis et, bibendum risus. Integer cursus, nibh in consectetur semper, ipsum mauris pharetra justo, sit amet varius dolor erat vel augue. Morbi interdum felis erat, non aliquet eros rhoncus eget. Fusce tempus, justo vitae egestas egestas, massa nisi facilisis erat, a eleifend odio ex vel nunc. Suspendisse sed nibh libero. Vivamus nec sollicitudin nibh. Nunc lacus sem, imperdiet nec sagittis quis, facilisis accumsan lorem. Quisque finibus dapibus tincidunt. Integer feugiat sollicitudin gravida. Sed pellentesque molestie consequat. \
 \
Etiam a nisl tempus, porta lorem eu, dapibus sapien. Integer fermentum tincidunt urna, id dignissim nisl dictum id. Donec diam lorem, pellentesque ac dapibus sed, sollicitudin et tortor. Donec rutrum, ex a commodo ullamcorper, nisi mi hendrerit justo, vitae vestibulum sapien mi et felis. Etiam lacus ex, elementum suscipit ultricies eu, porttitor vitae dui. Maecenas fermentum varius feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur lacinia pharetra lectus, vitae mollis sapien ullamcorper vel. Praesent efficitur turpis egestas euismod fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur dapibus enim risus, mattis feugiat justo bibendum ultrices. Mauris interdum mattis enim vitae tempor. Sed lacinia ante vitae ultrices eleifend. Cras id lacus ut ante dapibus accumsan in sit amet mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. \
 \
Nulla neque sapien, eleifend nec nisl et, pharetra consequat justo. Donec orci erat, aliquam ut consequat in, semper nec nisi. Phasellus auctor augue ut laoreet ultricies. Nulla cursus, odio a ornare interdum, libero dolor commodo velit, vitae fermentum leo justo in libero. Phasellus porta nisl sit amet sapien finibus, a blandit erat cursus. Cras interdum dolor in rutrum egestas. Suspendisse vitae est ligula. Nunc id nulla id eros fermentum rutrum eu ornare dui. Curabitur sit amet lobortis elit. \
 \
Maecenas a elit eros. Mauris sit amet diam tempor, fringilla velit nec, gravida ipsum. Sed suscipit sed ante non dictum. Curabitur et sagittis odio. Pellentesque auctor eu massa lacinia maximus. Sed ut felis vitae velit feugiat gravida. Mauris fringilla neque venenatis pretium vestibulum. Suspendisse luctus semper arcu vitae viverra. Nunc a rutrum ex, nec tempus nunc. Nam luctus neque interdum est vulputate, eu elementum libero efficitur. Pellentesque ac commodo mi. Phasellus et nulla odio. Fusce pellentesque eleifend lorem vel cursus. \
 \
Donec interdum auctor libero id molestie. Cras at sagittis felis, ac sollicitudin elit. Sed cursus tincidunt nibh, at pretium urna dapibus ut. Nullam eleifend sagittis risus at vehicula. Vivamus consectetur porta pharetra. Aenean in ullamcorper tellus, a posuere quam. Donec vulputate mi eget iaculis lobortis. Praesent ut leo nisi. \
 \
Duis tempus eu nibh ut rhoncus. Phasellus dapibus mollis leo, id ultrices felis vehicula ac. In hac habitasse platea dictumst. Duis accumsan odio eros, at sollicitudin ex porttitor a. Morbi ac risus quis eros tempor dapibus. Phasellus sit amet porta urna, vel blandit nunc. Pellentesque eget fermentum odio. Mauris rutrum libero nisi, pellentesque tempor justo scelerisque vitae. Aenean molestie dolor dolor, eget ultricies ligula vehicula a. Ut cursus volutpat efficitur. In imperdiet quis felis quis tempor. Nunc lectus risus, porttitor quis ipsum ut, euismod dapibus dui. Proin sed dolor non ligula fermentum pharetra vel tincidunt augue. Praesent ullamcorper est quis convallis sollicitudin. Morbi tristique, est id consequat lacinia, velit nulla viverra sapien, quis porttitor magna quam non tellus. \
 \
In posuere arcu odio. Duis dignissim egestas pharetra. Suspendisse ut urna eu ante interdum aliquet quis vel turpis. Quisque molestie tristique vehicula. Nullam efficitur mollis vehicula. Suspendisse malesuada nisi ac felis commodo placerat. Nullam diam enim, congue id elit ac, rutrum lobortis nunc. \
 \
Nulla nec laoreet elit, vel eleifend lacus. Integer lorem risus, sodales id magna at, tincidunt fermentum magna. Phasellus laoreet vehicula nulla, ac ultricies tortor tempus ultrices. Sed eu nisi quis libero cursus vestibulum at sit amet erat. Phasellus quis ipsum ut magna tincidunt pharetra sollicitudin sed ligula. Sed eget porta arcu, sed semper arcu. Etiam congue, sem sed ultrices dapibus, tellus ipsum porta turpis, quis consequat felis quam in ante. Nullam aliquet libero non velit molestie tincidunt. Vivamus tempor nunc tempor dolor tristique suscipit. \
 \
Duis ac lacus eu dui mollis porta at sit amet sapien. Suspendisse bibendum ligula ac odio facilisis porta. Curabitur luctus risus et posuere blandit. Donec id risus et nulla venenatis commodo. Sed congue, augue vitae venenatis eleifend, tellus massa ornare purus, vel semper purus neque id orci. Donec iaculis feugiat ex in porttitor. Etiam vel ultricies ipsum. Etiam condimentum lectus ut tincidunt fringilla. Aliquam diam odio, rhoncus vitae mattis at, sodales et ligula. \
 \
Quisque eu ligula ultrices, scelerisque nunc vel, ultricies risus. Vivamus at nisi sapien. Sed eu consequat enim. Pellentesque rhoncus ultrices massa, eget cursus nibh scelerisque eu. Pellentesque convallis dui non consequat viverra. Vestibulum enim quam, rutrum ac mattis in, varius quis orci. Fusce tempor euismod risus, quis venenatis diam consequat ac. Pellentesque sed augue quis orci elementum tristique. \
 \
Vestibulum nec tellus consectetur, sollicitudin libero eget, gravida magna. Nulla facilisi. Donec tempor blandit vestibulum. Donec elementum, magna et sollicitudin placerat, elit felis viverra massa, ut elementum nunc dolor at nulla. Nam faucibus nulla eget egestas cursus. Etiam ac massa condimentum, volutpat neque eu, ornare massa. Duis nisi sapien, consequat sit amet nisl at, condimentum eleifend orci. Proin fermentum venenatis imperdiet. Aliquam facilisis eget velit in ornare. Praesent dignissim, sem in sagittis venenatis, purus ligula tincidunt nisl, nec tincidunt mi nisi bibendum ex. Pellentesque finibus vel nisl a sodales. Vivamus tempus ultrices purus ut consequat. Proin ornare nisl tortor, sed facilisis lacus accumsan ut. Nulla dapibus lorem augue, ut suscipit est porta ac. \
 \
Fusce bibendum arcu congue urna feugiat laoreet. Morbi iaculis, enim eu condimentum convallis, orci justo posuere justo, quis placerat nisi risus eu dolor. Donec laoreet mattis arcu vitae commodo. In quis mauris ullamcorper, sodales turpis vitae, gravida dui. Sed enim erat, iaculis at posuere ut, vulputate quis magna. Fusce elit libero, euismod id porttitor molestie, vestibulum vitae enim. Phasellus pretium pellentesque est pretium lobortis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam lobortis nunc tempor erat suscipit vehicula. Aliquam scelerisque ut velit vitae finibus. Proin in lacinia justo, eu vulputate augue. Suspendisse vitae varius neque. Donec fringilla est sit amet erat consequat dictum. Sed in risus sollicitudin, consequat lacus quis, pretium sem. Nullam blandit elit non felis scelerisque convallis. Duis quis orci sit amet sapien eleifend accumsan. \
 \
Etiam facilisis tempor quam vel pulvinar. Nunc est odio, luctus in nibh non, iaculis finibus neque. Morbi varius sagittis arcu, quis volutpat justo. Pellentesque quis dignissim augue. Mauris libero metus, imperdiet vitae ultricies in, congue vel dui. Ut dapibus placerat condimentum. Morbi sit amet enim in nisi dignissim pulvinar. Maecenas aliquam vestibulum diam, sit amet lacinia ex. Vestibulum feugiat, ante eget ultricies accumsan, purus dui interdum dui, interdum cursus tortor purus vel felis. Morbi eleifend lectus interdum ante sollicitudin, nec varius orci tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. \
 \
Sed lacinia ac tortor id gravida. Aenean sit amet fringilla massa. Donec tempus mauris eu mauris bibendum posuere. Phasellus interdum ut odio et ullamcorper. Nulla et nulla non purus luctus tempus. Pellentesque commodo eu diam ut rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed sit amet est tellus. Aenean malesuada felis nec ex pretium, vitae commodo odio placerat. Ut pretium leo urna, eget ultrices odio convallis tincidunt. Cras consequat leo sed tincidunt commodo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum cursus pellentesque augue aliquet eleifend. Phasellus eleifend, urna ut hendrerit pretium, erat quam tincidunt neque, feugiat condimentum ipsum sem quis dui. Sed cursus sapien magna, sit amet venenatis mauris commodo sed. Nulla iaculis, justo non vestibulum rutrum, ex mauris aliquet nunc, in ultricies eros urna eu tellus. \
 \
Vivamus ultrices turpis mi, ac eleifend nulla pharetra quis. Aliquam nec magna eu felis sagittis gravida a in metus. Ut porttitor finibus risus, eget bibendum turpis lacinia id. Maecenas interdum vulputate risus, eu luctus arcu tristique tristique. Integer blandit blandit nisi. Mauris convallis feugiat tellus sit amet feugiat. Sed ac pellentesque felis. Suspendisse pretium gravida interdum. Proin fermentum lacinia urna fermentum bibendum. Aenean condimentum est vitae volutpat condimentum. Pellentesque semper enim vitae nulla varius lacinia congue quis lectus. Proin ac massa ac arcu iaculis imperdiet. Nullam aliquet odio non est convallis volutpat. Quisque dignissim placerat mi, et laoreet risus convallis quis. \
 \
Sed pretium lacus neque, sed pretium nibh ornare vitae. Aliquam laoreet enim enim, vitae mollis tortor viverra vel. Nullam egestas dolor vulputate diam tristique convallis. In ultricies id nibh eu vestibulum. Etiam ullamcorper, sapien in tempor posuere, nulla massa euismod eros, eu gravida erat ante ac felis. Sed dignissim ipsum quis urna pulvinar, volutpat iaculis ipsum facilisis. Donec lorem felis, condimentum vel lacus et, viverra viverra sem. Phasellus eleifend lacinia tellus, quis varius mauris gravida non. Quisque commodo orci sit amet enim dictum dignissim. Suspendisse finibus feugiat bibendum. \
 \
Maecenas eget magna nec sem pharetra luctus et consequat nulla. Donec eu nibh id mi eleifend sodales. Donec pellentesque felis vitae ante rutrum fringilla. Vivamus at nisi sit amet arcu finibus sodales vitae non mi. Phasellus quis dapibus dui. Sed eget imperdiet augue. Mauris sed elementum urna, sit amet aliquet tellus. Curabitur non blandit eros. Vivamus ultricies ornare magna, ac euismod mauris varius ac. In volutpat non urna quis posuere. Fusce imperdiet ullamcorper massa, facilisis elementum velit porttitor ut. In hac habitasse platea dictumst. Integer vulputate, justo quis euismod feugiat, tortor neque fermentum augue, nec elementum ante dolor quis sem. Duis laoreet sodales est at posuere. Morbi feugiat, est ut volutpat tincidunt, erat elit molestie massa, ac fringilla libero eros ut lorem. \
 \
Phasellus tempor, elit a molestie consequat, felis nisi vehicula leo, id fermentum purus ligula non libero. Mauris molestie est sit amet urna finibus, quis ullamcorper neque mattis. In tempor velit euismod, placerat arcu quis, finibus dui. Donec at mauris porta, eleifend ex vitae, finibus nisl. Vivamus scelerisque orci dictum nunc pulvinar, eu gravida urna efficitur. Vestibulum in ipsum dignissim, sodales tellus non, sagittis ante. Praesent a mattis orci. Proin maximus mattis pretium. Nullam pretium velit sed elementum auctor. Duis suscipit sollicitudin mauris, quis faucibus leo ornare quis. Ut metus est, efficitur ut semper eu, imperdiet at mi. Aliquam rhoncus turpis sed mi hendrerit, sit amet mollis purus pellentesque. Praesent sed efficitur ante. Duis at iaculis neque. Vestibulum sit amet enim ut felis pharetra posuere. \
 \
Donec sem orci, pellentesque ut urna eu, fringilla bibendum nisi. Donec nec augue vitae odio sodales tincidunt. Aenean ut lacinia sapien, at placerat justo. Donec at elementum purus, a consequat massa. Sed rhoncus pretium lectus quis dignissim. Nullam in purus vitae tortor lobortis scelerisque vel non tortor. Donec pellentesque sagittis cursus. Suspendisse id justo id nulla sagittis dictum nec vel massa. In quis metus bibendum, placerat ipsum quis, gravida risus. Sed euismod bibendum nibh, et luctus sem dignissim ornare. Cras id nunc vel lacus scelerisque blandit nec ut lorem. Vestibulum ultricies facilisis pretium. \
 \
Morbi ac arcu non eros iaculis dapibus et id nisl. Cras eu malesuada ligula, finibus facilisis mauris. Mauris sodales neque nec lectus feugiat cursus. Proin ut mi at massa condimentum pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tortor dui, ultrices ac sagittis vitae, scelerisque in enim. Sed nec semper nunc, ut congue lacus. Cras nulla nisl, porttitor.";

const target = "thisstringdoesn'texist";
console.log("Text length =", verylongstring.length, "Target length =", target.length);

console.time("Long search x 1000");
for (let i = 0; i < 1000; i++) {
    indexOfWithDist(verylongstring, target, 3);
}
console.timeEnd("Long search x 1000");
